[features]
seeds = false
[programs.devnet]
sesame = "2GTUkXFnABGVHFMqT1tVofBLPrBTAxzjb4Z2rpeMGsJG"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"#localnet
wallet = "/Users/grrwahrr/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
